### ISSUE TITLE
Documentation for generating resources

### ISSUE THREAD

**Issue by deepfry0** [rhtconsulting/puppet-jboss_admin#100] opened 2016-01-27 16:29 UTC
We are currently leveraging the jboss_admin module to manage our JBoss EAP Infrastructure. The version at hand is EAP 6.3, but we are looking to rollout 6.4 as a supported version. It would be great if there is a step-by-step document/tutorial outlining what needs to be done to generate resources for 6.4. Even better if the steps can be made generic so that the same logic can be applied when EAP 7 is ready for deployment.

**Comment by itewk** [comment] 2016-01-27 16:43
@cpitman  is this something you can knock out?

**Comment by itewk** [comment] 2016-01-27 16:46
@deepfry0 very good point.
I am going to direct you over to this Issue #34 though as this is a duplicate of that.

You may also be interested in the conversation here https://github.com/rhtconsulting/puppet-jboss_admin/issues/64

**Closed** 2016-01-27 16:46 UTC
Labels: documenation, duplicate
